- name: Install nvim
  homebrew: name=nvim
  tags:
    vim

- name: Install Packer
  ansible.builtin.git:
    repo: 'https://github.com/wbthomason/packer.nvim'
    dest: "~/.local/share/nvim/site/pack/packer/start/packer.nvim"
    depth: 1
  tags:
    vim
